### ISSUE TITLE
Completion for template files is not working

### ISSUE THREAD

**Issue by NicolasCW** [aemide/issue-tracker#8] opened 2024-09-11 11:06 UTC
It is not possible to use completion for template files. This is a disadvantage when using a lot of templates in the html of components.

**Approval.java**
```
String getDateApproval() {
  return "12-12-2012";
}
```

**approval.html**
```
<sly data-sly-use.model="com.aem.ide.test.Approval"
     data-sly-use.commonTemplate="templates/commonTemplate.html"
>
<sly  data-sly-call="${commonTemplate.itemtemplate @ item = model}"></sly>
```

**commonTemplate.html**
```
<template data-sly-template.itemtemplate="${@ item = 'item'}">
  ${item.dateApproval}
</template>
```

In the file commonTemplate.html, the completion is not working.

**Comment by karollewandowski** [comment] 2024-09-11 19:41
Thank you for reporting the issue.

Unfortunately, this is not a trivial problem. In theory, we could check the template calls and determine the param type by values passed to these calls. However, templates are usually implemented first, and there are no calls at this moment, so we wouldn't be able to determine the type.

A better, IMHO, solution would be to add information about the type in the parameter hint, for example:
```html
<template data-sly-template.itemtemplate="${@ item='com.example.Approval'}">
  ${item.dateApproval}
</template>
```

The problem is that this custom solution ties the code with the plugin, and some programmers may be against it. Also, there must be a way to make it compatible with usual hints, for example:
```html
<template data-sly-template.itemtemplate="${@ item='Approval item'}">
  ${item.dateApproval}
</template>
```

A solution to this would be to parse any non-simple (with package) class name and assume the first found class name is the required type, for example:
```html
<template data-sly-template.itemtemplate="${@ item='Approval item. Must be of com.example.Approval type.'}">
  ${item.dateApproval}
</template>
```

The problem would appear if there were two class names and the second would be the param class name, for example:
```html
<template data-sly-template.itemtemplate="${@ item='Approval item returned from com.example.Project.getApproval(). Must be of com.example.Approval type.'}">
  ${item.dateApproval}
</template>
```

To solve this, it should be possible to point the type explicitly, for example, by wrapping it into brackets:
```html
<template data-sly-template.itemtemplate="${@ item='Approval item returned from com.example.Project.getApproval(). Must be of [com.example.Approval] type.'}">
  ${item.dateApproval}
</template>
```

What do you think? I also encourage others to comment.

**Comment by NicolasCW** [comment] 2024-09-17 07:38
The first solution seems to be ok for me. The plugin will try to bind the template with the class in comment and not if it's impossible to find the class, and so in that last cast, it will be the same as now.

**Comment by karollewandowski** [comment] 2024-10-08 19:51
I think that we should go with mixing two solutions:
- if there is a fully-qualified class name only in the hint (for example, `item = 'com.example.Approval'`), then it is considered a parameter type
- if there is additional text describing the param, brackets are required (for example, `item = 'Approval item returned from com.example.Project.getApproval(). Must be of [com.example.Approval] type.'`)

**Comment by garthbongers** [comment] 2024-10-08 20:52
This would be great, and is a feature I would use _constantly_! I think the mixing of these two solutions would provide great flexibility.

**Comment by karollewandowski** [comment] 2024-12-03 08:07
Hi, it has been implemented and should be released in 30 minutes to the EAP channel:
https://plugins.jetbrains.com/plugin/9269-aem-ide/docs/early-access-program.html

Please update to 2024.3.1-eap7.

Implemented approach. The parameter type is retrieved from:
- option value if specified. Type can be specified as the only value or in brackets. Supported values examples:
  - fully-qualified names: `java.lang.String`, `java.lang.Integer`, `java.util.List<java.lang.String>`, etc.
  - simplified names - it works only for a set of `java.lang` classes. Examples: `String`, `Integer`, `Double`, `Boolean`, etc. Simplified names don't work together with fully-qualified names, so you can't do: `java.util.List<String>`
  - simplified names lowercase - it works only for a set of `java.lang` classes. Examples: `string`, `integer`, `int`, `double`, `boolean`, etc. Simplified names don't work together with fully-qualified names, so you can't do: `java.util.List<int>`
- inferred from template usage. The plugin searches for template calls and determines the type. If multiple usages pass a different type, the union type will be inferred, for example: `String | String[]`.

Inferred parameter types are provided with inlay hints, so they are displayed if a type is not specified explicitly.
<img width="970" alt="Screenshot 2024-12-03 at 09 06 09" src="https://github.com/user-attachments/assets/d2206c71-7dfb-4750-8bc1-8c110f1ac687">

Clicking on the type name with Cmd or Ctrl will go to the type declaration.

Please test and provide your feedback.

**Closed as completed** 2024-12-05 18:57 UTC

**Comment by HitmanInWis** [comment] 2024-12-09 14:22
amazing addition to the plugin, extremely useful.  I had built a manual workaround for the missing code completion, because it is that important. Still necessary for folks that dont have this plugin, but for folks that do this is a huge improvement upon HTL's limitation of not being able to strongly type template parameters.
